💄Item 상세정보를 볼 수 있는 UI 구현이 완료되었습니다.
DeveloperAcademy-POSTECH/MacC-Dime-Vincent pull request #10
Opened 2022-10-10 15:41 UTC by Rookie0031

## 배경
#1 작업과 같은 ItemTappedView이며 PR분량 조절을 위해 분할해서 진행했습니다. 유저는 이 뷰에서 판매 물품에 대한 상세정보와 판매자의 정보를 알 수 있습니다.

## 작업 내용 (Content)
## PageController + ScrollView
 이미지를 손가락으로 옆으로 쓸어넘기면 자연스럽게 다음 이미지로 교체됨과 동시에 페이지 컨트롤러로 총 이미지의 개수와 현재 보는 이미지의 인덱스를 작은 동그라미들로 보여주는 UI입니다.

 이는 scrollView와 pageControl을 혼합해서 구현합니다.
스크롤뷰는 컨텐츠가 많고 제한된 프레임으로 보여주는 것입니다.

 뷰의 너비와 이미지의 width를 같게하고, 이미지 4장을 컨텐트뷰에 배치시킵니다.
그럼 스크롤할 때 사실은 contentView contetoffset이 변화하면서 contentView다른 영역을 보여주는 것인데, 마치 이미지가 딱 교체되는 것같은 효과를 낼 수 있습니다. 그리고 스크롤할 때마다 delegate 함수를 호출하고 그 함수를 통해 pageController의 현재 페이지 인덱스를 바꿔줄 수 있습니다.

![IMG_DBC05712DFF2-1](https://user-images.githubusercontent.com/103009135/194903707-2b2106be-5a6c-49be-acf7-923b95289873.jpeg)

## UITextView 내 글자숫자에 따른 높이 동적변화
텍스트뷰는 너비를 지정해주면 텍스트가 많아지면 그에 맞춰 height가 높아지게 됩니다. 하지만 레이아웃을 잡는 과정에서 어쩔 수 없이 기본으로 높이를 지정해주는데 레이아웃 priority를 250으로 낮춰주면 텍스트가 많아질 때의 우선순위보다 레이아웃

1. 제목이 두줄로 바뀌면 그 height가 달라지면서 밑의 사용률과 며칠전 레이블이 살짝 위로 올라갈 수 있음 
2. textView 는 설명의 길이차이에 따라 차이가 많이 날 것 같아서 동적 레이아웃을 시도함 

## 스크린샷
![Simulator Screen Recording - iPhone 13 - 2022-10-11 at 00 41 05](https://user-images.githubusercontent.com/103009135/194904538-1224665b-4b79-4f6c-9600-b9aba13a8df6.gif)

## 참고문서, 레퍼런스
- 작업을 하면서 참고한 문서 및 레퍼런스를 작성합니다.

2022-10-11 00:30 UTC, Kim-Yeon-ho submitted a review, later dismissed
LGTM!

2022-10-11 00:30 UTC, Kim-Yeon-ho commented on Vincent/Global/Supports/SceneDelegate.swift
> +        window?.rootViewController = ItemTappedViewController()
머지될때 시작화면을 맞추는 게 필요할 것 같다고 생각이 듭니다!
각자마자 작업이 다르긴 하지만 TabbarView를 default로 해놓고 작업한 부분을 주석으로 처리하고 표현하는건 어떨까용

2022-10-11 00:30 UTC, Kim-Yeon-ho commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +    }()
then을 일부러 쓰지 않은 건가요!?

2022-10-11 00:30 UTC, Kim-Yeon-ho commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +    }()
이 부분도 그렇습니다!

2022-10-11 00:30 UTC, Kim-Yeon-ho commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +        $0.text = "해커켄"
🫣

2022-10-11 00:30 UTC, Kim-Yeon-ho commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +    let id: String
id값이 String인 이유는 ItemInfo들을 구별할때 사용자의 아이디로 구별하기 위함일까요?

2022-10-11 00:32 UTC, Rookie0031 commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +    }()
아 이거 다른 파일에서 Then안쓰고 작업하다가 복붙해서 그렇게 되었네요 ㅋㅋㅋㅋㅋㅋㅋ 바꾸겠습니다

2022-10-11 00:33 UTC, Rookie0031 commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +    let id: String
그렇게 해도 좋겟네요 ㅋㅋㅋㅋㅋㅋ 그걸 의도한건 아니고 일반적으로 UUID.toString같은거로 문자열로 하길래 일단은 저렇게 해놨습니니다

2022-10-11 00:38 UTC, Rookie0031 commented on Vincent/Global/Supports/SceneDelegate.swift
> +        window?.rootViewController = ItemTappedViewController()
좋습니다!!

2022-10-11 00:53 UTC, Kim-Yeon-ho commented
develop브랜치 리뷰어 2명설정하고 바로 머지되는 것 막아놨습니다 지금은 루키만 admin에서 한단계 내렸는데 다른 사람들도 설정해야할 것 같네요 @Rookie0031

2022-10-11 00:55 UTC, obtusa07 commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +        $0.isScrollEnabled = false
이 설정을 통하면 글자수가 영역을 벗어나는경우 말줄임표(...)로 끝나나요?

2022-10-11 01:07 UTC, obtusa07 commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +
P1 
제목이랑 본문에 터치하면 수정이 가능하게 됩니다 ㅎㅎㅎㅎ

2022-10-11 01:13 UTC, obtusa07 commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +    // TODO: dynamic size로 변경 필요
P1
현재 SE 시뮬레이터에서 끝까지 스크롤이 안 되는 문제가 있습니다. 스크롤뷰의 영역설정이 잘못된거 같습니다.

2022-10-11 01:14 UTC, obtusa07 approved these changes
현장에서 대화를 나눠본 결과 UI 완성 기한까지 14시간밖에 안 남은점을 고려하여 나중에 리팩토링을 진행하기로 했습니다.
코멘트에 달아놓은 문제들을 해결해야 하며 CollectionView로 리팩토링을 진행할수도 있을거 같습니다.

2022-10-11 11:23 UTC, cozytk commented
잘 보고 갑니다 ^^

2022-10-11 11:25 UTC, obtusa07 commented
> 잘 보고 갑니다 ^^

보셨으면 스타 눌러주세요

2022-10-11 11:38 UTC, Kim-Yeon-ho commented
> 잘 보고 갑니다 ^^

보고가는거 공짜 아니에요

2022-10-11 11:53 UTC, cozytk commented
> > 잘 보고 갑니다 ^^
> 
> 보셨으면 스타 눌러주세요

그정도는 아니에요

2022-10-11 23:10 UTC, Rookie0031 commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +
감사합니다! 바로 반영했습니다

2022-10-11 23:13 UTC, Rookie0031 commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +        $0.isScrollEnabled = false
텍스트뷰는 지정한 height 이상으로 텍스트가 많아지면 위아래로 스크롤이 가능하게 됩니다. 스크롤을 막아놓은 것입니다

2022-10-12 05:36 UTC, PecanPiePOS commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +        $0.isScrollEnabled = false
[p5]
LGTM

2022-10-12 06:01 UTC, PecanPiePOS requested changes
[p2]

2022-10-12 06:01 UTC, PecanPiePOS commented on Vincent/Screens/ItemTapped/ItemTappedViewController.swift
> +    }
image 가 다 보여야 하는데 정방형으로 보여야 하므로 
참고 링크 : https://sujinnaljin.medium.com/ios-%EC%82%AC%EC%A7%84%EC%9C%BC%EB%A1%9C-%EB%B3%B4%EB%8A%94-aspectfit-aspectfit-scaletofill-f41470d0191f

2022-10-12 12:03 UTC, PecanPiePOS approved these changes

2022-10-12 12:03 UTC, Kim-Yeon-ho approved these changes

2022-10-12 12:04 UTC, Rookie0031 commented
## Fix
수정사항이 있으나 1차 머지 이후 추후 버그 수정 작업 예정입니다.

2022-10-12 12:04 UTC, merged