💄/12 home view UI
DeveloperAcademy-POSTECH/MacC-Dime-Vincent pull request #22
Opened 2022-10-12 08:53 UTC by obtusa07

## 배경
- 피그마 요구사항에 맞게 HomeVIew의 UI를 그려야합니다.
- HomeVIew는 사용자가 서비스를 이용하기 위해 가장 먼저 마주하는 View입니다. 해당 영역에서 수행되어야 하는 기능은 프로필 조회, 원하는 물건 검색, 카테고리로 분류된 아이템 조회 그리고 최신순으로 나열된 아이템을 보는 것입니다
- 해당 영역은 상단의 서치바까지의 HeaderView 영역과 CollectionView 영역으로 구성됩니다.
- CollectionView에서 Compositional Layout를 이용했습니다. 최소 지원 버전이 iOS13이라는 점 그리고 HomeView에서 보여줘야 하는 기능중 스크롤과 복잡한 화면을 보여줘야한다는 점을 고려하여 결정했습니다.

## 작업 내용 (Content)
- collectionView은 두 세션으로 나뉩니다.
- 첫번째 세션은 카테고리를 만들기 위한 세션입니다. 4개의 버튼을 2줄로 만들어 총 8개의 카테고리 버튼을 구성합니다.
- 두번째 세션은 하디가 만들고 있는 것과 같은 아이템이 위치하는 곳입니다. UI를 그리는 것은 완료했지만 Data를 처리하는 문제에 있어 하디가 그리는 화면과 동일한 부분이 있다는 것을 자각하여 데이터를 세부적으로 어떻게 그릴지에 대해서 논의를 해야하는 상황입니다.

## 스크린샷
<p align="left">
  <img width="200" alt="스크린샷1" src="https://user-images.githubusercontent.com/47441965/195294893-6c6708dd-3495-4934-a317-8ff75da8fa87.png">
</p>

## 테스트방법
- SE와 14 Pro, 14 ProMax에서 확인했습니다.
- SE의 경우 배경화면으로 설정된 그림이 살짝 위로 올라가는것을 관찰했습니다. contentMode 설정문제로 보입니다. 해당 이슈는 모든 화면에서 배경화면을 그릴때 고려해야 하는 점을 고려하여 해결이 필요합니다.

## PR & Issues
- #3 , #21

## 향후 작업사항
- 데이터소스를 연결해야합니다.
- 하디와 같은 collectionView를 다른 방식으로 개발했기 떄문에 이것에 대해 합의가 필요합니다.
- 다양한 상황에서 화면이 어떻게 움직일지 합의가 필요합니다.
- 
## 참고문서, 레퍼런스

https://developer.apple.com/documentation/uikit/views_and_controls/collection_views/implementing_modern_collection_views
https://snapkit.github.io/SnapKit/docs/
https://ios-development.tistory.com/945
https://zeddios.tistory.com/169
https://www.youtube.com/watch?v=y1uXXVUu43o

2022-10-12 13:31 UTC, Rookie0031 commented on Vincent/Screens/Home/HomeViewController.swift
> +            switch section {
p3
section이 Int 타입으로 지정되어있어서 어떤 부분의 레이아웃을 담당하는지 한눈에 알기 어렵습니다.
이 부분은 enum을 활용하여 케이스 분류하면 좋을 것 같습니다.

2022-10-12 13:38 UTC, Rookie0031 commented on Vincent/Screens/Home/HomeCategoryCell.swift
> +protocol ReusableView: AnyObject {
p3
삭제해도 무방한 코드인것같습니다!

2022-10-12 14:00 UTC, coby5502 approved these changes
흠터레스팅...

2022-10-12 14:00 UTC, coby5502 commented on Vincent/Global/Base/BaseViewController.swift
> +        //button.addAction(buttonAction, for: .touchUpInside)
제 PR에서 고쳤습니다

2022-10-12 14:00 UTC, coby5502 commented on Vincent/Global/Extensions/UILabel+Extension.swift
> +            //lineBreakStrategy = .hangulWordPriority
제 PR에서 고쳤습니다

2022-10-12 14:11 UTC, Rookie0031 requested changes
## 고생하셨습니다!

compositional layout 적용이 쉽지않았을텐데 잘 적용된 것 같습니다. 
코드 양식 통일화 및 구조 개선 진행해주시면 좋을 것 같습니다!

2022-10-12 14:11 UTC, Rookie0031 commented on Vincent/Screens/Home/HomeViewController.swift
> +                item.contentInsets.trailing = 16
p2
contentInsets이 trailing에만 적용되어 있어 중앙 정렬이 안되고 있습니다! 그래서 leading과 trailing을 동일하게 적용하면 레이아웃이 훨씬 깔끔해질 것 같습니다!

2022-10-12 14:11 UTC, Rookie0031 commented on Vincent/Screens/Home/HomeViewController.swift
> +        collectionView.dataSource = self
p2
datasource 및 delegate 설정은 함수로 따로 빼서 관리하면 좋을 것 같습니다! render에는 레이아웃과 관련된 부분만 모아놓으면 유지관리가 더 용이할 것 같기 때문입니다!

2022-10-13 00:31 UTC, obtusa07 commented on Vincent/Screens/Home/HomeViewController.swift
> +        var cv = UICollectionView(frame: .zero, collectionViewLayout: layout)
완료했습니다!

2022-10-13 00:32 UTC, obtusa07 commented on Vincent/Screens/Home/HomeViewController.swift
> +    static let categoryHeaderID = "카테고리"
위치 재조정 완료했습니다

2022-10-13 00:32 UTC, obtusa07 commented on Vincent/Screens/Home/HomeViewController.swift
> +                item.contentInsets.trailing = 16
item에도 값을 주어 동일한 위치에 정렬되도록 조치했습니다

2022-10-13 01:30 UTC, Rookie0031 approved these changes

2022-10-13 01:34 UTC, obtusa07 commented on Vincent/Screens/Home/HomeViewController.swift
> +            switch section {
하디와 리펙토링을 진행하면서 하겠습니다

2022-10-13 01:34 UTC, obtusa07 commented on Vincent/Screens/Home/HomeCategoryCell.swift
> +protocol ReusableView: AnyObject {
해당 코드 파일 자체가 삭제예정이라 지금은 두겠습니다!

2022-10-13 05:00 UTC, closed without merging