:sparkles: 파이어베이스 회원가입 및 로그인 추가
DeveloperAcademy-POSTECH/MacC-Dime-Vincent pull request #39
Opened 2022-10-14 02:01 UTC by coby5502

## 배경
- 작업이 이루어진 이유

## 작업 내용 (Content)
- 회원가입 기능 추가
- 로그인 기능 추가

## 스크린샷
- 화면 전환이나 인터렉션이 있는 경우엔 GIF, 정적인 화면이라면 스크린샷을 이용합니다.

<p align="left">
  <img width="200" alt="스크린샷1" src="사진URL">
  <img width="200" alt="스크린샷2" src="사진URL">
  <img width="200" alt="스크린샷3" src="사진URL">
</p>

## 테스트방법
- PR리뷰어가 변경사항을 확인할 수 있는 방법을 서술합니다.

## PR & Issues
- 현재 작성 중인 Pull Request와 관련된 PR과 Issues가 있다면 나열합니다.

## 참고문서, 레퍼런스
- 작업을 하면서 참고한 문서 및 레퍼런스를 작성합니다.

2022-10-14 03:20 UTC, coby5502 reviewed
홧팅~

2022-10-14 03:20 UTC, coby5502 commented on Vincent/Global/Extensions/Sequence+Extension.swift
> +}
나중에 데이터들을 여러개를 불러올 때, async/await 처리를 하도록 도와주는 코드입니다.

코드 예시입니다.
```
        await meetingIds?.asyncForEach({ (meetingId: String) in
            guard let meeting = await FirebaseManager.shared.getMeeting(meetingId: meetingId) else { return }
            meetings.append(meeting)
        })
```

2022-10-14 03:20 UTC, coby5502 commented on Vincent/Global/Supports/AppDelegate.swift
>      }
메세지 푸쉬알람을 주고받으려면, 사용자 기기의 토큰값이 필요합니다.
추후 작업할 채팅 기능을 위해, 토큰값을 넣는 코드를 미리 추가하였습니다.

2022-10-14 03:20 UTC, coby5502 commented on Vincent/Global/Supports/SceneDelegate.swift
>      }
로그인 여부에 따라, 메인화면과 로그인화면으로 넘어가도록 설정하였습니다.

2022-10-14 07:17 UTC, Rookie0031 approved these changes
고생하셨습니다!

2022-10-14 07:17 UTC, Rookie0031 commented on Vincent/Global/Utils/PushNotificationSender.swift
> +        let paramString: [String : Any] = ["to" : token,
p5
"to", "notification", "data" 는 코비가 설정해놓은 DTO 인가요?

2022-10-14 07:17 UTC, Rookie0031 commented on Vincent/Screens/Login/LoginViewController.swift
> +        emailField.becomeFirstResponder()
p5
이메일 입력을 맨 먼저하게 하기 위한 코드인가요?

2022-10-14 07:51 UTC, coby5502 commented on Vincent/Global/Supports/AppDelegate.swift
>      }
네 맞습니다!!

2022-10-14 07:52 UTC, coby5502 commented on Vincent/Global/Utils/PushNotificationSender.swift
> +        let paramString: [String : Any] = ["to" : token,
아뇨아뇨 그낭 예전에 가져왔던 코드인데 메세지 알람 보낼때 쓰이는 파라미터 값들입니다

2022-10-14 07:53 UTC, coby5502 commented on Vincent/Screens/Login/LoginViewController.swift
> +        emailField.becomeFirstResponder()
네 맞아요 저 코드는 화면에 처음 들어왔을 때, 텍스트필드에 바로 키보드 입력이 되도록 합니다.

2022-10-14 13:30 UTC, Rookie0031 commented on Vincent/Global/Extensions/Sequence+Extension.swift
> +extension Sequence {
여기 엄청 잘되있어요 참고하시면 좋을 것 같습니다!
[동기/비동기, async await](https://sujinnaljin.medium.com/swift-async-await-concurrency-bd7bcf34e26f)

2022-10-14 14:42 UTC, obtusa07 requested changes

2022-10-14 14:42 UTC, obtusa07 commented on Vincent/Global/Supports/GoogleService-Info.plist
> +	<key>API_KEY</key>
p1
API 노출건에 대하여 확인하고 싶은것이 있습니다.
스푸핑과 같은 공격에 안전할까요? 보안설정이 어떻게 되어있는지 제가 확신이 없어서 여쭤봅니다.
저희가 Email/Password를 직접 인증을 거쳐서 진행하는데 그만큼 안전에 대해 생각해야 한다고 생각합니다.

https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public
https://firebase.google.com/docs/projects/api-keys

2022-10-14 14:43 UTC, obtusa07 commented on Vincent/Global/Extensions/Sequence+Extension.swift
> +extension Sequence {
감사합니다!

2022-10-14 15:18 UTC, Kim-Yeon-ho approved these changes
다른 분들이 잘 적어주셔서 그 부분 반영되면 좋을 것 같습니다! LGTM!

2022-10-15 05:11 UTC, coby5502 commented on Vincent/Global/Utils/PushNotificationSender.swift
> +        let server_key = "AAAAvWyUGFU:APA91bHKwd0IyOHA4v86X-NuBKcOTmpt-N1nOppmN94jMbj_Rcl9UrpwGgjlnZAL4gAI-cI2sQI2CtRyX_Qo5zxgZPdueJlM7KQc5ExshtOOtqKrDHaJOVZjL5u2jfSnOk4Aazna1_n3"
이거 지금 쓰는 키는 아니고, 예전 프젝에서 있던 키입니다.
나중에 비공개하는 방법도 알아볼게요!

2022-10-15 06:52 UTC, coby5502 commented on Vincent/Global/Extensions/Sequence+Extension.swift
> +extension Sequence {
코드 예시는 예를 들어놓았습니다

2022-10-15 06:55 UTC, coby5502 commented on Vincent/Global/Supports/GoogleService-Info.plist
> +	<key>API_KEY</key>
GoogleService-Info.plist의 경우 파베에서 직접 쓰라고 주는 파일이고, 가이드대로 진행하였습니다.
개인적으로 보안에 대해서 지식이 없어서, 어떻게 해야할지 잘 모르겠습니다.
스푸핑이 무엇인지, 대처하는 방법이 무엇인지... 지식 공유를 부탁드려요...

2022-10-16 09:21 UTC, obtusa07 commented on Vincent/Global/Supports/GoogleService-Info.plist
> +	<key>API_KEY</key>
월요일에 아이작과 대화를 하고 해당 부분 처리하기로 했습니다!
일단 Approve 드립니다.

2022-10-16 09:21 UTC, obtusa07 approved these changes

2022-10-16 09:23 UTC, merged